# -*- coding: utf-8 -*-
"""Earthquakes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q8861rL3ng-BebWYkhP-pV7LMXvZQ4y1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from google.colab import drive
drive.mount('/content/drive',force_remount=True)

"""importing datasets



    # directory_path='/content/drive/My Drive/Earthquakes/'

    datasets = []

    # for i in range(1, 24):
    #   Construct the file path for each CSV file
        file_path = f"{directory_path}dataset ({i}).csv"

    # Read the CSV file and append it to the datasets list
        dataset = pd.read_csv(file_path)
        datasets.append(dataset)

# merging the dataset

```
merged_dataset = pd.concat(datasets, ignore_index=True)

# Print the shape of the merged dataset to verify the concatenation
print("Shape of merged dataset:", merged_dataset.shape)
print(merged_dataset.tail(10))
```
"""

save_path = "/content/drive/My Drive/Earthquakes/MainCsv/merged_dataset.csv"


merged_dataset=pd.read_csv(save_path)
merged_dataset.head(10)

plt.plot(merged_dataset['mag'])

"""# modify the 'time' column to 'date' and removed time part and store time part in 'time' column

```
merged_dataset.rename(columns={'time': 'date'}, inplace=True)
merged_dataset['time'] = merged_dataset['date'].apply(lambda x: x.split('T')[1])
merged_dataset['date'] = merged_dataset['date'].apply(lambda x: x.split('T')[0])
print(merged_dataset.head(10))



```
#removed 'Z' part in the milisecond part

```
merged_dataset['time'] = merged_dataset['time'].apply(lambda x: x.replace('Z', ''))
print(merged_dataset.tail(10))
```
#save the modified dataset

```
save_path = "/content/drive/My Drive/Earthquakes/MainCsv/merged_dataset.csv"
merged_dataset.to_csv(save_path, index=False)
```




"""

total_dates = merged_dataset['date'].nunique()

print("Total number of unique dates:", total_dates)

merged_dataset.fillna(0, inplace=True)
print(merged_dataset.tail(10))

plt.plot(merged_dataset['mag'])